export const AnalyticsEvents: any = {
  MENU: 'HIKER_MENU',
  MENU_HOME: 'HIKER_MENU_HOME',
  MENU_ABOUT: 'HIKER_MENU_ABOUT',
  MENU_QUOTES: 'HIKER_MENU_QUOTES',
  MENU_MAPICS: 'HIKER_MENU_MAPICS',
  MENU_CONTACT: 'HIKER_MENU_CONTACT',
  CONTACT_EMAIL: 'HIKER_CONTACT_EMAIL',
  CONTACT_LINKEDIN: 'HIKER_CONTACT_LINKEDIN',
  CONTACT_INSTAGRAM: 'HIKER_CONTACT_INSTAGRAM',
  CONTACT_FACEBOOK: 'HIKER_CONTACT_FACEBOOK',
  CONTACT_TWITTER: 'HIKER_CONTACT_TWITTER',
  CONTACT_GITHUB: 'HIKER_CONTACT_GITHUB',
  MAPICS: 'HIKER_MAPICS'
}
